### ISSUE TITLE
Nagyon jó, pár apró szépséghiba

### ISSUE THREAD

**Issue by beni69** [pulikutya/M-k-d--Aknakeres--HTML-CSS-JS#1]
## Pár helyen belekötök, annak érdekében, hogy még jobb legyen:

- **A legnagyobb probléma, hogy valamikor nem érzékeli, hogy a bombákon kívül már minden mezőt felfedtem, avagy néha nem lehet nyerni.** *(szerintem az a baj, ha a mezőkön zászló van, de nem tudom annyira nem néztem utána)*
- A feladatleírás szerint kell, hogy legyen egy [README.md](https://github.com/pulikutya/M-k-d--Aknakeres--HTML-CSS-JS/new/master?readme=1) fájl amiben szerepel egy link a live weboldalhoz
- Tetszik, hogy a pálya szabadon átméretezhető, viszont a width *(szélesség)* és a height *(magasság)* fordítva vannak, ettől picit összezavaró lesz.
- A képek amik megjelennek *(zászló, bomba, stb)* azokat akkor tölti be, amikor először olyan szituáció alakul ki a játékban, hogy szükség lesz rájuk, ezáltal a játék reszponzivitása hagy még kívánni valót maga után. Ezt úgy lehet megoldani, hogy előre betöltöd ezeket a képeket, HTML-ben van erre beépített módszer, de nem lövöm le a poént, hagyom, hogy magadtól fedezd fel, keress rá, hogy HTML preload.
- A lerakott zászlókat jó, hogy számolja, de nem akadályoz meg abban, hogy több szászlót lerakj, mint amennyit lehetne, az értéket engedi, hogy negatív szám legyen.

**És kérlek, amikor javítod ezeket írj egy kommentet ide, ehhez az issue-hoz, hogy meg tudjam nézni.**

**Comment by pulikutya** [comment]
ok
