### ISSUE TITLE
Még pár hiba

### ISSUE THREAD

**Issue by beni69** [pulikutya/M-k-d--Aknakeres--HTML-CSS-JS#2]
- A mine és a mine exploded képek nincsenek preloadolva
- a width és height feliratok alapból kisbetűvel vannak, akkor viszont nagybetűvel lesznek, amikor átállítom

**Comment by beni69** [comment]
a width és height feliratok alapból kisbetűvel vannak, akkor viszont nagybetűvel lesznek, amikor átállítom

**Comment by pulikutya** [comment]
ok
